from models.leaderboard import Leaderboard


lb = Leaderboard()
lb.receive_answer(0, "diffty", "a")
lb.receive_answer(1, "diffty", "a")
lb.receive_answer(3, "diffty", "a")
lb.receive_answer(4, "diffty", "a")
lb.receive_answer(5, "diffty", "a")
lb.receive_answer(5, "diffty", "B")
lb.receive_answer(6, "diffty", "C")
lb.receive_answer(7, "diffty", "c")
lb.receive_answer(8, "diffty", "b")
lb.receive_answer(9, "diffty", "d")
lb.receive_answer(10, "diffty", "a")
lb.receive_answer(11, "diffty", "b")
lb.calculate_scores(0, "a")
lb.calculate_scores(1, "a")
lb.calculate_scores(2, "d")
lb.calculate_scores(3, "a")
lb.calculate_scores(4, "b")
lb.calculate_scores(5, "b")
lb.calculate_scores(6, "c")
lb.calculate_scores(7, "c")
lb.calculate_scores(8, "b")
lb.calculate_scores(9, "d")
lb.calculate_scores(10, "a")
lb.calculate_scores(11, "d")
lb.print_leaderboard()
